### ISSUE TITLE
andere naam

### ISSUE THREAD

**Issue by anoukbruinn** [moonlightlizaa/visual-thinking#5]
andere naam geven, je hebt namelijk content op je hele website en later weet je misschien niet meer waar je dit kan vinden.
https://github.com/moonlightlizaa/visual-thinking/blob/d11dfb8be0edca4328f470bb6509d42877717514/index.html#L52

**Comment by moonlightlizaa** [comment]
Ik ga het aanpassen! Bedankt voor de feedback! 😊
